//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> Otp { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> VerifiedEmail { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Role Role { get; set; }
    }
}
